WHILE LOOP

In [ ]:
while condition:
    expression

In [2]:
error = 50.0
while error>1:
    error=error/4
    print(error)

12.5
3.125
0.78125


FOR LOOP

In [ ]:
For var in seq:
    expression

In [6]:
dat = [1,2,3,4,5]
for i in dat:
    print(dat.index(i),i)

0 1
1 2
2 3
3 4
4 5


In [9]:
for index,i in enumerate(dat):
    print("index "+str(index)+": "+str(i))

index 0: 1
index 1: 2
index 2: 3
index 3: 4
index 4: 5


In [10]:
for c in "family":
    print(c.capitalize())

F
A
M
I
L
Y


In [11]:
# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
# Code the for loop
for index,area in enumerate(areas,start=1) :
    print("room " + str(index) + ": " + str(area))

room 1: 11.25
room 2: 18.0
room 3: 20.0
room 4: 10.75
room 5: 9.5


In [12]:
# house list of lists
house = [["hallway", 11.25], 
         ["kitchen", 18.0], 
         ["living room", 20.0], 
         ["bedroom", 10.75], 
         ["bathroom", 9.50]]
         
# Build a for loop from scratch
for i in house:
    print(f"the {i[0]} is {i[1]} sqm")

the hallway is 11.25 sqm
the kitchen is 18.0 sqm
the living room is 20.0 sqm
the bedroom is 10.75 sqm
the bathroom is 9.5 sqm


LOOPS IN DICTIONARIES 
mydict.items()

In [19]:
world = {
    "pakistan":14.5,
    "india":12,
    "aus":11
}

for key,value in world.items():
    print(key,str(value))

pakistan 14.5
india 12
aus 11


LOOPS IN ARRAYS np.ndtir(myarray)

In [ ]:
#1d array
import numpy as np
np_height=np.array([11,2,32,4])
np_weight=np.array([2,3,4,5])
bmi=np_weight/np_height ** 2
for val in bmi:
    print(val)

0.01652892561983471
0.75
0.00390625
0.3125


In [25]:
#d2 array
np_height=np.array([11,2,32,4])
np_weight=np.array([2,3,4,5])
bmi=np.array([np_weight,np_height])
for val in bmi:
    print(val)

[2 3 4 5]
[11  2 32  4]


did u see above it gives 1d array if we apply the same for loop on 2d array but we want elements so for that use numoy function that is *nditer()* , use as below :

In [26]:
#d2 array
np_height=np.array([11,2,32,4])
np_weight=np.array([2,3,4,5])
bmi=np.array([np_weight,np_height])
print(bmi)
for val in np.nditer(bmi):
    print(val)

[[ 2  3  4  5]
 [11  2 32  4]]
2
3
4
5
11
2
32
4


LOOPING ON PANDA DATAFRAMES

In [ ]:
import pandas as pd
data = pd.read_csv('data.csv',index_col=0)
for lab,row in data.iterrows():   #lab is index column and row shows row ka data
    print(lab)
    print(row)

BR
country       brazil
capital            a
population         1
Name: BR, dtype: object
RU
country       russia
capital            b
population         2
Name: RU, dtype: object
IN
country       india
capital           c
population        3
Name: IN, dtype: object
PA
country       pakistan
capital              d
population           4
Name: PA, dtype: object


In [28]:
for lab,row in data.iterrows():   #lab is index column and row shows row ka data
    print(lab+' : '+row['capital'])

BR : a
RU : b
IN : c
PA : d


In [29]:
for lab,row in data.iterrows():   #lab is index column and row shows row ka data
    data.loc[lab,"name_length"]=len(row['country'])
print(data)

     country capital  population  name_length
BR    brazil       a           1          6.0
RU    russia       b           2          6.0
IN     india       c           3          5.0
PA  pakistan       d           4          8.0


In [30]:
data['population']=data["population"].apply(lambda x:x+5)
print(data)

     country capital  population  name_length
BR    brazil       a           6          6.0
RU    russia       b           7          6.0
IN     india       c           8          5.0
PA  pakistan       d           9          8.0


In [32]:
data['summary']=data.apply(lambda row:f"{row['country']} population {row['population']}",axis=1 )
print(data)

     country capital  population  name_length                summary
BR    brazil       a           6          6.0    brazil population 6
RU    russia       b           7          6.0    russia population 7
IN     india       c           8          5.0     india population 8
PA  pakistan       d           9          8.0  pakistan population 9


In [34]:
data['length']=data["country"].apply(len)
print(data)

     country capital  population  name_length                summary  length
BR    brazil       a           6          6.0    brazil population 6       6
RU    russia       b           7          6.0    russia population 7       6
IN     india       c           8          5.0     india population 8       5
PA  pakistan       d           9          8.0  pakistan population 9       8
