In [24]:
import numpy as np

In [25]:
np.array([1,2,3])

array([1, 2, 3])

In [26]:
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

In [27]:
# convert the baseball into numpy array

In [28]:
np_baseball = np.array(baseball)

In [29]:
print(np_baseball)

[180 215 210 210 188 176 209 200]


In [30]:
type(np_baseball)  #nd means n dimensional

numpy.ndarray

In [31]:
height = [3,4.5,5.5,6] #convert this list into numpy first and then convert heights into meters

In [32]:
np_height = np.array(height)

In [33]:
np_height_m = np_height * 0.0254

In [34]:
print(np_height_m)

[0.0762 0.1143 0.1397 0.1524]


In [35]:
#it will convert different dtypes into one dtype
np.array([1,True,3]) + np.array([4,5,False])

array([5, 6, 3])

In [36]:
#indexing and sub-array is same as python list
height[3]
height[2:]

[5.5, 6]

In [37]:
height.shape

AttributeError: 'list' object has no attribute 'shape'

In [ ]:
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

In [ ]:
#convert baseball into np array
np_baseball = np.array(baseball)
print(np_baseball)

[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]


In [ ]:
np_baseball.shape

(4, 2)

In [ ]:
np.array([1,2,3,4])*np.array([10,4,3,9])

array([10,  8,  9, 36])

In [ ]:
np.array([1,2,3,4])*np.array([10,4,3])

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [40]:
#generating random data to work on 
heightnew = np.round(np.random.normal(1.75,0.20,10),2)

In [41]:
weightnew = np.round(np.random.normal(60.32,15,10),2)

In [42]:
np_city = np.column_stack((heightnew,weightnew))

In [43]:
print(np_city)

[[ 1.96 58.81]
 [ 1.83 44.27]
 [ 1.57 64.26]
 [ 2.13 69.41]
 [ 1.62 44.07]
 [ 1.93 39.05]
 [ 1.57 49.12]
 [ 1.68 66.64]
 [ 1.98 47.43]
 [ 1.52 75.55]]


In [44]:
np.mean(np_city[:,0])

np.float64(1.779)

In [45]:
np.median(np_city[:,0])

np.float64(1.755)

In [46]:
np.corrcoef(np_city[:,0],np_city[:,1])

array([[ 1.        , -0.17152506],
       [-0.17152506,  1.        ]])

In [47]:
np.std(np_city[:,0])

np.float64(0.2028028599403864)

In [48]:
np_city.size

20

In [49]:
np_city.dtype

dtype('float64')

##4. *Array Initialization Functions*

In [50]:
print(np.zeros((2,3)))   # 2x3 array with zeros
print(np.ones((3,3)))    # 3x3 array with ones
print(np.arange(0,10,2)) # values from 0 to 8 step=2
print(np.linspace(0,1,5)) # 5 values between 0 and 1

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


##*2. Important Attributes*

In [51]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)

print("ndim (dimensions):", arr.ndim)   # 2D array
print("shape (rows, cols):", arr.shape) # (2, 3)
print("size (total elements):", arr.size) # 6
print("dtype (data type):", arr.dtype) # int64 (system dependent)

Array:
 [[1 2 3]
 [4 5 6]]
ndim (dimensions): 2
shape (rows, cols): (2, 3)
size (total elements): 6
dtype (data type): int64


##*Mathemaical operations*


In [52]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)  # [5 7 9]
print(a - b)  # [-3 -3 -3]
print(a * b)  # [4 10 18]
print(a / b)  # [0.25 0.4  0.5]
print(a ** 2) # [1 4 9]


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


##*Aggregate Functions*

In [55]:
arr = np.array([1,2,3,4,5,6])

print("Sum:", arr.sum())        # 15
print("Max:", arr.max())        # 5
print("Min:", arr.min())        # 1
print("Mean:", arr.mean())      # 3.0
print("Standard Deviation:", arr.std())  # 1.41
print("Median:", np.median(arr)) # 3.0

Sum: 21
Max: 6
Min: 1
Mean: 3.5
Standard Deviation: 1.707825127659933
Median: 3.5


In [58]:
reshaped = arr.reshape(3,2)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [59]:
flattend = reshaped.flatten()
print(flattend)

[1 2 3 4 5 6]


In [61]:
np.random.randint(1,10,size=4)

array([1, 1, 7, 3], dtype=int32)

In [62]:
np.random.rand(3)

array([0.06330523, 0.98304613, 0.23812613])

In [65]:
np.random.rand(2,3)

array([[0.24067073, 0.18706498, 0.99813511],
       [0.24343258, 0.60445806, 0.49395166]])

In [67]:
x = np.array([1,2,3])
y = np.array([4,5,6])
c=np.concatenate([x,y])
print(c)
d=np.array_split(c,3)
print(d)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
