In [1]:
import numpy as np

In [3]:
data = np.arange(1,100,2)

In [7]:
data.size

50

In [8]:
data.shape

(50,)

In [10]:
data.reshape(5,10)

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69, 71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89, 91, 93, 95, 97, 99]])

In [11]:
data.dtype

dtype('int64')

In [16]:
data2 = np.arange(1,101)

In [17]:
data2.reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [19]:
student1=np.array([10,20,30,40])
student2=np.array([50,60,70,1])

In [21]:
#mathematical operation
print(student1+student2)
print(student1-student2)
print(student1*student2)
print(student1/student2)

[ 60  80 100  41]
[-40 -40 -40  39]
[ 500 1200 2100   40]
[ 0.2         0.33333333  0.42857143 40.        ]


In [23]:
#aggragation
print(np.sum(data))
print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(np.max(data))
print(np.min(data))


2500
50.0
50.0
28.861739379323623
99
1


In [25]:
data3 = np.arange(1,13)

In [26]:
data3.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
data4 = np.arange(1,13)

In [32]:
concatenated = np.concatenate([data4,data3])

In [33]:
np.split(concatenated,3)

[array([1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 9, 10, 11, 12,  1,  2,  3,  4]),
 array([ 5,  6,  7,  8,  9, 10, 11, 12])]

In [35]:
#filter
print(data4[data4>5])

[ 6  7  8  9 10 11 12]


In [38]:
#toss simulation
tosses=np.random.randint(0,2,size=50)
head = np.sum(tosses==1)
tail = np.sum(tosses==0)
print(head)
print(tail)

23
27


In [41]:
#dice role simulation
dice = np.random.randint(1,7,size=1000)
print(dice)
sixes=np.sum(dice==6)
print(sixes)


[3 1 1 1 3 2 1 2 2 1 3 3 6 6 1 3 3 5 4 2 2 4 4 5 1 5 4 1 3 1 5 1 2 3 4 4 4
 1 6 6 6 1 5 2 1 4 1 5 4 2 4 5 5 3 1 5 4 2 6 5 5 4 2 3 3 5 6 1 2 1 5 1 4 5
 6 3 4 3 3 1 5 3 3 1 6 5 3 3 1 3 6 3 3 5 3 6 3 3 2 4 1 3 6 3 6 3 6 5 3 1 3
 4 1 5 2 6 3 1 6 4 3 5 5 3 5 1 6 4 4 1 4 3 5 6 5 1 4 6 6 2 4 3 6 6 3 6 6 4
 3 3 1 3 4 6 5 6 2 2 6 3 1 5 3 1 1 3 5 4 1 6 1 4 6 3 6 3 4 2 4 2 3 5 2 6 2
 4 1 4 2 5 6 4 3 6 5 5 4 4 6 6 2 4 2 5 2 3 1 2 2 4 6 1 2 2 3 4 2 1 3 3 4 4
 3 6 6 5 2 2 6 6 6 1 1 4 1 5 4 1 5 3 2 4 1 5 2 5 3 2 4 6 4 1 4 4 2 2 1 6 3
 3 1 2 2 1 3 3 1 4 3 3 4 3 1 4 2 3 4 2 6 1 3 4 6 3 1 5 5 2 3 6 3 2 3 4 6 4
 6 5 6 2 6 3 5 4 5 5 5 4 5 4 6 5 5 3 3 6 2 4 5 6 3 5 5 3 3 4 2 5 4 1 4 4 2
 3 6 2 3 5 3 5 6 1 4 4 4 2 6 3 2 5 6 1 1 1 6 6 4 6 5 4 5 6 5 3 3 3 5 1 1 6
 2 5 2 5 1 5 4 1 5 1 4 5 5 1 1 6 1 5 4 3 3 5 6 3 6 5 4 3 2 4 5 4 2 5 4 2 1
 2 1 4 6 3 3 6 1 5 1 1 5 3 5 5 2 6 6 2 6 5 4 2 1 6 3 4 2 2 1 1 5 2 6 6 3 4
 3 5 5 6 2 4 6 2 2 5 1 3 3 4 3 6 3 1 3 2 6 5 1 3 2 2 5 6 5 2 3 6 4 3 2 1 6
 1 3 5 4 6 5 6 5 5 1 1 3 

In [42]:
np.full((2,2),8)

array([[8, 8],
       [8, 8]])

In [44]:
np.linspace(0,1,5) #0 sai 1 kai darmiyan 5 values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [45]:
np.eye(3,3) #identity matrix banata hai

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
new = np.random.randint(1, 21, (3,3)) #Ek random 3x3 matrix banao integers ke sath [1–20]

In [50]:
print(data4.ndim)
print(data4.size)
print(data4.shape)
print(data4.dtype)

1
12
(12,)
int64


In [52]:
new.T #transpose

array([[19, 16,  8],
       [ 9, 20,  5],
       [17,  9, 14]], dtype=int32)

In [53]:
print(np.random.rand(2,3))

[[0.25516079 0.35965022 0.14915065]
 [0.11913373 0.20630575 0.55692717]]


In [ ]:
print(np.random.randint(2,10,12))  #integers generate kar rhai hain

[3 8 9 5 7 2 5 6 5 9 6 5]


In [ ]:
print(np.random.randint(2,10,(2,3))) #matrix generate kar rahi hainn

[[6 9 4]
 [4 5 8]]


In [62]:
#Ek 3x3 matrix banao np.arange(1,10).reshape(3,3) aur uska 2nd row aur 3rd column ka element print karo.
arr= np.arange(1,10).reshape(3,3)
print(arr)
print(arr[1:2,2:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[6]]


In [63]:
print(arr[0:2,0:2])

[[1 2]
 [4 5]]
